version: '3'
services:
  distance_service:
    build: ./distance_service/
    container_name: dc_service
    env_file:
      - .env
  
  price_calculation_service:
    build: ./price_calculation_service/
    container_name: price_service
    depends_on:
      - distance_service
    env_file:
      - .env
    ports:
      - "8080:4567"