# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trippb.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "trippb.Point" do
    optional :lat, :double, 1
    optional :long, :double, 2
  end
  add_message "trippb.Trip" do
    optional :startPoint, :message, 1, "trippb.Point"
    optional :endPoint, :message, 2, "trippb.Point"
  end
  add_message "trippb.TripInfoResponse" do
    optional :distance, :int64, 1
    optional :duration, :int64, 2
  end
end

module Trippb
  Point = Google::Protobuf::DescriptorPool.generated_pool.lookup("trippb.Point").msgclass
  Trip = Google::Protobuf::DescriptorPool.generated_pool.lookup("trippb.Trip").msgclass
  TripInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("trippb.TripInfoResponse").msgclass
end
