// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trippb.proto

package trippb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_trippb_40c95de829c30098, []int{0}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type Trip struct {
	StartPoint           *Point   `protobuf:"bytes,1,opt,name=startPoint,proto3" json:"startPoint,omitempty"`
	EndPoint             *Point   `protobuf:"bytes,2,opt,name=endPoint,proto3" json:"endPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trip) Reset()         { *m = Trip{} }
func (m *Trip) String() string { return proto.CompactTextString(m) }
func (*Trip) ProtoMessage()    {}
func (*Trip) Descriptor() ([]byte, []int) {
	return fileDescriptor_trippb_40c95de829c30098, []int{1}
}
func (m *Trip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trip.Unmarshal(m, b)
}
func (m *Trip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trip.Marshal(b, m, deterministic)
}
func (dst *Trip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trip.Merge(dst, src)
}
func (m *Trip) XXX_Size() int {
	return xxx_messageInfo_Trip.Size(m)
}
func (m *Trip) XXX_DiscardUnknown() {
	xxx_messageInfo_Trip.DiscardUnknown(m)
}

var xxx_messageInfo_Trip proto.InternalMessageInfo

func (m *Trip) GetStartPoint() *Point {
	if m != nil {
		return m.StartPoint
	}
	return nil
}

func (m *Trip) GetEndPoint() *Point {
	if m != nil {
		return m.EndPoint
	}
	return nil
}

type TripInfoResponse struct {
	Distance             int64    `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TripInfoResponse) Reset()         { *m = TripInfoResponse{} }
func (m *TripInfoResponse) String() string { return proto.CompactTextString(m) }
func (*TripInfoResponse) ProtoMessage()    {}
func (*TripInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_trippb_40c95de829c30098, []int{2}
}
func (m *TripInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripInfoResponse.Unmarshal(m, b)
}
func (m *TripInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripInfoResponse.Marshal(b, m, deterministic)
}
func (dst *TripInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripInfoResponse.Merge(dst, src)
}
func (m *TripInfoResponse) XXX_Size() int {
	return xxx_messageInfo_TripInfoResponse.Size(m)
}
func (m *TripInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TripInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TripInfoResponse proto.InternalMessageInfo

func (m *TripInfoResponse) GetDistance() int64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *TripInfoResponse) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "trippb.Point")
	proto.RegisterType((*Trip)(nil), "trippb.Trip")
	proto.RegisterType((*TripInfoResponse)(nil), "trippb.TripInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TripInfoClient is the client API for TripInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TripInfoClient interface {
	GetTripInfo(ctx context.Context, in *Trip, opts ...grpc.CallOption) (*TripInfoResponse, error)
}

type tripInfoClient struct {
	cc *grpc.ClientConn
}

func NewTripInfoClient(cc *grpc.ClientConn) TripInfoClient {
	return &tripInfoClient{cc}
}

func (c *tripInfoClient) GetTripInfo(ctx context.Context, in *Trip, opts ...grpc.CallOption) (*TripInfoResponse, error) {
	out := new(TripInfoResponse)
	err := c.cc.Invoke(ctx, "/trippb.TripInfo/GetTripInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripInfoServer is the server API for TripInfo service.
type TripInfoServer interface {
	GetTripInfo(context.Context, *Trip) (*TripInfoResponse, error)
}

func RegisterTripInfoServer(s *grpc.Server, srv TripInfoServer) {
	s.RegisterService(&_TripInfo_serviceDesc, srv)
}

func _TripInfo_GetTripInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Trip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripInfoServer).GetTripInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trippb.TripInfo/GetTripInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripInfoServer).GetTripInfo(ctx, req.(*Trip))
	}
	return interceptor(ctx, in, info, handler)
}

var _TripInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trippb.TripInfo",
	HandlerType: (*TripInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTripInfo",
			Handler:    _TripInfo_GetTripInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trippb.proto",
}

func init() { proto.RegisterFile("trippb.proto", fileDescriptor_trippb_40c95de829c30098) }

var fileDescriptor_trippb_40c95de829c30098 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0xed, 0xee, 0x5a, 0xca, 0xb4, 0x42, 0x99, 0x53, 0xe9, 0x49, 0x72, 0xd2, 0x43, 0x7b,
	0xa8, 0x07, 0x1f, 0xc0, 0x83, 0xe8, 0x49, 0x82, 0x0f, 0x60, 0x6a, 0xa3, 0x04, 0x4a, 0x12, 0x92,
	0xf1, 0xfd, 0x25, 0xd3, 0x0f, 0x7a, 0xd8, 0xdb, 0xfc, 0x3f, 0x66, 0x7e, 0x30, 0x50, 0x51, 0x30,
	0xde, 0x8f, 0xbd, 0x0f, 0x8e, 0x1c, 0xe6, 0x8b, 0x12, 0x1d, 0xdc, 0x7e, 0x38, 0x63, 0x09, 0x6b,
	0x38, 0xcf, 0x8a, 0x9a, 0xec, 0x3e, 0x7b, 0xc8, 0x64, 0x1a, 0x11, 0xe1, 0x32, 0x3b, 0xfb, 0xdb,
	0x9c, 0xd8, 0xe2, 0x59, 0x7c, 0xc1, 0xe5, 0x33, 0x18, 0x8f, 0x1d, 0x40, 0x24, 0x15, 0x88, 0x77,
	0x79, 0xa9, 0x1c, 0xee, 0xfa, 0x95, 0xc0, 0xa6, 0x3c, 0x14, 0xf0, 0x11, 0x0a, 0x6d, 0xa7, 0xa5,
	0x7c, 0xba, 0x56, 0xde, 0x63, 0xf1, 0x0e, 0x75, 0x22, 0xbc, 0xd9, 0x1f, 0x27, 0x75, 0xf4, 0xce,
	0x46, 0x8d, 0x2d, 0x14, 0x93, 0x89, 0xa4, 0xec, 0xb7, 0x66, 0xd6, 0x59, 0xee, 0x9a, 0xb3, 0xbf,
	0xa0, 0xc8, 0x38, 0xcb, 0xa7, 0x53, 0xb6, 0xea, 0xe1, 0x05, 0x8a, 0xed, 0x16, 0x3e, 0x43, 0xf9,
	0xaa, 0x69, 0x97, 0xd5, 0xc6, 0x4f, 0x4e, 0xdb, 0x1c, 0xd5, 0x11, 0x2d, 0x6e, 0xc6, 0x9c, 0x1f,
	0xf6, 0xf4, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xea, 0x4b, 0xe8, 0x40, 0x01, 0x00, 0x00,
}
